### ISSUE TITLE
the ePIC should not be a separate publication system

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-configurable-content-donders#12]
it uses a handle, just like the "Handle persistent identifier". From publication_system.json 

```
   {
      "system":"European persistent identifier consortium",
      "pidType":"ePIC",
      "urlPrefix":"http://hdl.handle.net/"
   },
   {
      "system":"Handle persistent identifier",
      "pidType":"handle",
      "urlPrefix":"http://hdl.handle.net/"
   },
```

I consider ePIC related to Handle, just like Elsevier is related to DOI.

**Comment by hurngchunlee** [comment]
Well ... ePIC, to my opinion, is similar to DOI, an organisation maintains/guarantees an infrastructure for distribution and delivering handle indexes.  If some institute maintains its own infrastructure for handle indexes, it's not necessary to be ePIC.

**Comment by robertoostenveld** [comment]
but ePIC is not managing the infrastructure. It only acts as registrar. I think that [DONA](https://www.dona.net/handle_system/) is in charge of managing.  

whois handle.net does not show anything useful.

whois doi.org does show that its admin organization is the International DOI Foundation, which also legally exists (i.e. they pay [tax](http://990finder.foundationcenter.org/990results.aspx?action=Find&fn=doi&st=&ei=)). 

Elsevier is indeed different; it is not a registrar, only a user. 

So ePIC is perhaps to Handle as [these](https://www.doi.org/registration_agencies.html) are to DOI.

**Comment by robertoostenveld** [comment]
@EricMaris what do you think about this issue?

**Comment by hurngchunlee** [comment]
I don't think ePIC is just operating the handle registry ... it does more.  Have you seen this website and the services it provides: http://www.pidconsortium.eu

**Comment by robertoostenveld** [comment]
Yes, they do more, just like godaddy doing more. But that does not put godaddy in charge of the DNS system, nor means that the godaddy system is separate from the DNS system.

However, reading the 2nd paragraph on handle.net makes me realize that CNRI (who has their website behind handle.net) is only in charge of the “20.500” subsection… On DONA you can see that "International DOI Foundation” is also a Multi-Primary Administrators. We already realized before that DOI and Handle are technically the same and that both these work

http://hdl.handle.net/11633/di.dccn.DSC_3018015.03_369
http://doi.org/11633/di.dccn.DSC_3018015.03_369

My issue with ePIC is that it is listed towards the researchers/end-users as system next to Handle and DOI, whereas I don’t see it as separate system. Researchers themselves don’t have anything to do with ePIC. You cannot look up an ePIC ID on epic.org or any other ePIC website.
