### ISSUE TITLE
README file for content editor

### ISSUE THREAD

**Issue by hurngchunlee** [donders-research-data-management/rdm-configurable-content-donders#21]
@robertoostenveld, @EricMaris I have started updating the README file and writing a specific one for content editors.  Could you have a look of my first attempt?

**Comment by robertoostenveld** [comment]
I don't think it is realistic that Miriam, Bernhard or Jessica do the testing. I would even doubt that @EricMaris would manage that. Those are the people I have in mind as content-managers. I think this is more realistic

```
1. The content manager edits contents on the master branch.
2. The content manager informs system administrator to update the system with the changes.
3. The system administrator tests changes on the master branch.
4. The system administrator merge changes in the master branch into the release branch.
5. The system administrator/content manager receive a notification about the deployment process.
```

By whom or by which process is the notification in step 5 being sent? How does that person/process who the content managers are? Or is the notification done through github (where the content manager can be identified)?

**Comment by robertoostenveld** [comment]
I also propose to be consistent in using "content editor" rather than "content manager"

**Comment by hurngchunlee** [comment]
Is content editor more suitable than content manager?  I searched the text in this repository, I always use content manager.

**Comment by robertoostenveld** [comment]
you used "content editor" in the issue title ;-) 

I feel that editor is slightly more appropriate, because we use manager elsewhere (related to collections). And the editor/manager cannot fully manage by him/herself, but needs the system administrator to check/merge/deploy.

Now that I think of it, the process would be like this
- edit
- communicate (to the sysadmin)
- check
- merge
- deploy
- communicate (back to the editor)

**Comment by hurngchunlee** [comment]
Maybe identifying the following two roles is better:

- content editor: the role which is responsible for editing the content and communicate to the content manager, e.g. Jessica and Miriam.
- content manager: the role which is responsible for checking and merging changes into release branch. A person like me. 

I don't think system administrator should be mentioned here as the scope of "system" is vague.  Furthermore, if I try to identify the actions the system admin should take (i.e. deploying to production and informing content manager).  Those actions have already been automated. 

Who should take what role can be implemented in various ways in different institutes.  In DI, I can imaging that the data stewards, you and Eric are content editors, and I am the content manager; while in BSI, I can imaging that Rob has both roles at the moment.  However, I think the content manager should be added to receive the notification email, as this is currently the way the system administrator communicates back to the content manager.

In github, the content manager also has the "admin" permission of the repository so that he/she can grant edit permission to new content editors in his/her institute.

**Comment by robertoostenveld** [comment]
I agree with the "content editor" and "content manager".

Would this not be better documented on https://donders-research-data-management.github.io/rdm-wiki/en/#!administration/ together with other documentation aimed at the people that maintain the system?

**Comment by robertoostenveld** [comment]
One more thought regarding the place of the documentation: if it is specific per institute, it makes sense to have it in the configurable content. If it applies to all instances/institutes, it should be at a higher (more general) level.

**Comment by EricMaris** [comment]
I'm sorry for the late reply. It's teaching season(-;)

1. I agree with the distinction between the content editor and the content manager role. I expect content editors (e.g., data stewards) to only make changes on the Github web interface. For all command-line operations, per repository, a content manager should be assigned.
2. With respect to documentation, we should first distinguish between documentation for end users, which is on the RU-CMS, and documentation for support staff, which could go on a GibHub-hosted wiki. The institutes are responsible for the former.
3. For the documentation for support staff (which includes the management of the configurable content), I propose we make use of a single GitHub-hosted wiki that contains both institute-**a**specific information (e.g., the information in the readme file on how to update configurable content), and institute-specific information in a separate section. The content in the institute-specific information is under the responsibility of the institute.

**Comment by robertoostenveld** [comment]
Regarding 2 and 3: we already have documentation for support staff, and that is currently on github in the rdm-wiki. But Miriam and Bernhard do not have github accounts (that I know off) and therefore cannot contribute to documentation (or configurable content). I think yhey should decide together with @jesask what the best place is for them to maintain their documentation. Until then, we should ensure that the documentation does not further scatter.

**Comment by hurngchunlee** [comment]
I think we should move the README documents away from the repository, given that they may be modified irrelevant to the change of the static content itself.  It's a bit over killing that changes on README triggers redeployment of the static content; but on the other hand, we like to keep changes synced into the release branch.

As Robert suggested, I will move these documents into the rdm-wiki repository.

**Comment by hurngchunlee** [comment]
I have moved the documentations to the rdm-wiki: http://donders-research-data-management.github.io/rdm-wiki/en/#!administration/configurable_content.md
