### ISSUE TITLE
text on the front page should be updated

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-configurable-content-donders#23]
Hi @hurngchunlee, could you update the numbers in the following front-page text?

This repository is being used by 324 researchers to manage their research data, organized in 192 work-in-progress and 6 finalized data acquisition collections, 113 work-in-progress and 2 finalized research documentation collections and 31 work-in-progress and 13 finalized data sharing collections. You can request access to the data sharing collections.

**Comment by hurngchunlee** [comment]
I have updated the numbers.

**Comment by hurngchunlee** [comment]
... and merged into release branch.

**Comment by robertoostenveld** [comment]
thanks!
