### ISSUE TITLE
evaluate the help pages hosted on the RDM site

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-configurable-content-donders#38]
Hi @jesask, can you please check out https://data.donders.ru.nl/doc/help/

I copied all text as discussed. The official links from the help button and from the (?) buttons still points to the RU CMS, so users will not see this yet. The internal links on the new pages still need to be updated, they are now still pointing to the RU CMS. Also, most images are still obtained from the RU CMS. 

Copying the documentation and reading it once more, I realize that the hierarchical structure is rather deep and therefore it is not very clear what to find where.

@hadrianswall, could you also take a look?

**Comment by jesask** [comment]
Hi @robertoostenveld, I think findability of info really decreases with the absence of the navigation - and side bar.. If it is not possible to configure this, would it be possible to add other ways of navigation, e.g. add related pages on top of each page? (I do like the way it is presented at the bottom now but don't want to always scroll to the bottom.. Also for the FAQs, to me the side bar is really necessary. Although the hierarchical structure is already quite deep, without navigation / side bar it would be even more needed?

**Comment by robertoostenveld** [comment]
In the migration I did not want to change any content or structure, hence the same content and layout. 

I am also not happy about the navigation, but neither about the 25(!) pages at 4 levels that the documentation presently spans. I totally understand why the Nature editor could not find the documentation he was looking for. 

But the actual content formatting works quite well and I do like that it is now shown inside the donders repository page and format. So I do think it deserves more work to try and improve on this first attempt. We should think about flattening the structure and consider adding a proper table-of-content to some of the pages rather than just listing the pages on the next level.

I propose that we discuss this at the next core meeting. Perhaps you can also discuss this with @hurngchunlee, he will know what the system can do in terms of presenting structure.

**Comment by robertoostenveld** [comment]
Since the help button is now linked to the new documentation under doc/help, there is nothing more to do here.
