### ISSUE TITLE
include figures when building "doc"

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-configurable-content-donders#39]
I fixed the "img src" of https://data.donders.ru.nl/doc/help/research_circle.png but it still appears as broken at the bottom on https://data.donders.ru.nl/doc/help/rdm-nutshell.html. I guess it is because images are not included in the build Makefile. Could you add all png and jpg documents under doc/help?

**Comment by hurngchunlee** [comment]
Fixed it.
