### ISSUE TITLE
the external_urls.json needs to be updated

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-configurable-content-donders#49]
right now the (?) help buttons still point to the (old!) documentation on the RU CMS. This should be updated to point to the corresponding help items under doc/help.

**Comment by robertoostenveld** [comment]
I believe it only applies to these ones

```
  "collections.header" : "http://www.ru.nl/donders/research/data/faq/get-started/#h11c325e4-dbac-4ce9-a903-6b349ae3336c",
  "editCollectionModal.form.ethicalApprovalsBorder" : "http://www.ru.nl/donders/research/data/faq/get-started/#h35a6ab14-4886-4955-b888-d574621c5713",
  "editCollectionModal.form.ethicalApprovalsLabel" : "http://www.ru.nl/donders/research/data/faq/get-started/#h35a6ab14-4886-4955-b888-d574621c5713",
  "editCollectionModal.form.meshKeywordsBorder" : "http://www.ru.nl/donders/research/data/faq/get-started/#hc738a7fa-dcf8-4046-9051-0b3b4aedd10d",
  "editCollectionModal.form.meshKeywordsLabel" : "http://www.ru.nl/donders/research/data/faq/get-started/#hc738a7fa-dcf8-4046-9051-0b3b4aedd10d",
  "editCollectionModal.form.sfnKeywordsBorder" : "http://www.ru.nl/donders/research/data/faq/get-started/#hd52a3e99-1250-43dc-9203-4397db955132",
  "editCollectionModal.form.sfnKeywordsLabel" : "http://www.ru.nl/donders/research/data/faq/get-started/#hd52a3e99-1250-43dc-9203-4397db955132",
  "editCollectionModal.header-label" : "http://www.ru.nl/donders/research/data/user-manual/get-started/edit-your-collection-details/",
  "oneTimePasswordModal.explanationLink" : "http://www.ru.nl/donders/research/data/user-manual/transfer-data/",
```

**Comment by hurngchunlee** [comment]
@jesask - could you have a look of those URLs and update them accordingly to point to the new help?

**Comment by jesask** [comment]
Ok, done. Currently pointing to FAQ 'sections' on the webportal though because of the current FAQ pages format. I will update this .json again if FAQ format is updated in future

**Comment by hurngchunlee** [comment]
@jesask you could just put the reference point (specified in RST document) as HTML anchor at the end of the path; but with lowercase.

As an example, I have implemented links to specific FAQ for MeSH and SFN. The example can be found via the following link:

https://github.com/donders-research-data-management/rdm-configurable-content-donders/commit/4bfb397559c377f67381175b565b744415c5fad6

**Comment by jesask** [comment]
Ok thanks, done!

**Comment by hurngchunlee** [comment]
The changes are deployed to the production. Closing the issue.
