### ISSUE TITLE
doc/dua/index unclear

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-configurable-content-donders#53]
<img width="880" alt="screen shot 2019-02-27 at 14 31 55" src="https://user-images.githubusercontent.com/899043/53493805-8d36d180-3a9c-11e9-90cc-7cf10c66fe57.png">

the rst file is newer than the index.html.

it is not clear to me which of the two files contains the authorative content. Can you clarify?

**Comment by hurngchunlee** [comment]
The file is created by Jessica.  I am not aware of this RST file.  Escalating to Jessica ...

@jesask Could you please have a look?

**Comment by jesask** [comment]
I created this file with the intention of making this dua doc editable to us (data stewards) - so that we do not have to edit in html. I think it should in that sense replace the index.html; I'm not sure now though whether this dua_index.rst is actually used or how to make sure it replaces the index.html; @hurngchunlee can you help?

**Comment by hurngchunlee** [comment]
Given the current implementation of the build process, the RST file in this directory will NOT be converted to HTML.  If you want to achieve what you mentioned, you should put this RST file in the help/ directory, and the build process will pick it up and convert it to a HTML.  After that you could change the external_urls.json file to point to the URL of the converted HTML file (e.g. https://data.donders.ru.nl/help/dua_index.html).

Furthermore, I don't think you want the side panel of the help documents to be shown on this converted HTML page.  I will have to instruct the build process to skip adding the side panel to this page, explicitly.   Let me know if this is really what you want, or you could just stay with editing the html file.

**Comment by jesask** [comment]
Ok; bit inconsistent but we'll edit the html file instead, it's not such a big issue. I'm happy with the current link to the /doc/dua, without sidepanel etc. I removed the dua_index.rst file

**Comment by robertoostenveld** [comment]
I think this has been resolved. If not, please reopen this issue and explain.
