### ISSUE TITLE
Mounting WebDav directly with Windows file browser should be removed from the help documentation

### ISSUE THREAD

**Issue by hurngchunlee** [donders-research-data-management/rdm-configurable-content-donders#54]
@jesask It is known that the Windows native WebDav client is problematic and not up to the standard.  For that, Utrecht University will develop their own driver on WIndows that can replace the one used for the file explorer.  For the time being, we should remove the network-drive mounting paragraph for windows off the help documentation, and put a message saying mounting network drive on Windows is NOT supported.

**Comment by hurngchunlee** [comment]
Already add a warning on this page: https://data.donders.ru.nl/doc/help/user-manual/transfer-data/mount-network-drive.html

**Comment by robertoostenveld** [comment]
I think the warning is clear enough and that this issue is resolved. If you disagree, please reopen this issue and update the documentation.
