### ISSUE TITLE
privacy policy and other html

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-configurable-content-donders#6]
@hurngchunlee 

Wednesday we agreed that the privacy policy is to be represented on a single html page on the RDM CMS. I just found some other “content" to which probably the same reasoning applies: In the leftovers at https://github.com/Donders-Institute/rdm-wiki/tree/master/en/leftovers there are still the DUAs. 

Should those also go to the RDM system?

I also suggest to rethink the organization a bit. We now have (according to https://github.com/donders-research-data-management/rdm-ontology/blob/master/external_urls.json)

http://data.donders.ru.nl/doc/homepage/homepage.html
http://data.donders.ru.nl/doc/logout/logout.html
etc

which seems to mimic the organization in the rdm-ontology repo, except that it is mixed with non-html pieces (like the json and jenkins files). 

I suggest we change it such that we have in the repo all sections in the “doc” directory
rdm-ontology/doc/homepage.html
rdm-ontology/doc/login.html
rdm-ontology/doc/logout.html
rdm-ontology/doc/logout.html
rdm-ontology/doc/privacy_policy.html
etc
and on the website 
http://data.donders.ru.nl/doc/homepage.html
http://data.donders.ru.nl/doc/login.html
http://data.donders.ru.nl/doc/logout.html
http://data.donders.ru.nl/doc/logout.html
http://data.donders.ru.nl/doc/privacy_policy.html

For the future maintainers (like Jessica, Berend or a 10% PhD student) this will be much more logical.

I would also put the DUAs in html format under doc in the repo and on the website.

Even section such as 
http://data.donders.ru.nl/doc/email/collectionChangesLeadText.html
and managerLessCollectionsLeadText.html can be under doc, without the trailing "email" directory. 

And (as before) I suggest that the https://github.com/donders-research-data-management/rdm-ontology/blob/master/privacy/privacy_policy.md is only represented as a html snippet. I don’t think that anyone but you (and me a bit) cares about markdown and an automatic conversion. We can live without the automatic conversion (but keep the md2html script, which might still be handy). The reason to insist is that I want the (current and future) documentation and instruction team to understand the overall system better, which means to simplify the technical details.

**Comment by robertoostenveld** [comment]
looking at https://github.com/donders-research-data-management/rdm-ontology/blob/master/dua/index.json I realize that it points to txt files. I suppose these txt snippets are now inserted in the RDM CMS.

I think that html snippets should be inserted instead (and these should be served by the web server).

yes, I just found this one
http://data.donders.ru.nl/doc/dua/BSD.txt

**Comment by hurngchunlee** [comment]
Displaying DUA in CMS assumes the content of it is in "plain-text".  Technically speaking, it wraps the "plain-text" with "<pre> </pre>".  Changing it requires CMS to remove the wrapping.  I would suggest the following:

- reorganise those accepted by CMS as HTML snippets
- add one JIRA item to change the CMS expectation, and within the same item, add a subtask to migration all DAU's from plain text to HTML format

For the first action, we can do it independently to CMS.  @robertoostenveld: Will you reorganise them or shall I do it?

**Comment by hurngchunlee** [comment]
btw, who is going to convert DUA's to HTML.  I see a lot of work needed.

**Comment by robertoostenveld** [comment]
I have converted all txt to html snippet. Only 4 or 5 are "rich" html, most are simply pre-formatted (as they were before). We can ask a person assigned to documentation to format it more nicely (but there is no urgency to that). 

@hurngchunlee can you make the jira item to change from txt to html?

**Comment by robertoostenveld** [comment]
this has been resolved and merged in #14
